### ISSUE TITLE
Please add the support for object/hash

### ISSUE THREAD

**Issue by Nixie24** [lsdsjy/prettier-plugin-stylus#10]
Please add the support for object/hash.I really need it.
I can't understand the functions of "child" and "children" in src/index.ts, so I can't contribute codes.

**Comment by lsdsjy** [comment]
Hi! `child` and `children` are related to a concept named `path` in prettier. You can learn more about it in this post: https://medium.com/@fvictorio/how-to-write-a-plugin-for-prettier-a0d98c845e70

**Comment by Nixie24** [comment]
Though I'm not a native English speaker, and I had some problems reading the passage, I finally add the support for `Object/hash` and `Member`.

**Comment by lsdsjy** [comment]
That's excellent! Would really appreciate it if you open a PR to this repo.

**Comment by Nixie24** [comment]
I've already open the PR. #11

**Comment by ipadhim** [comment]
[# 11](https://github.com/lsdsjy/prettier-plugin-stylus/pull/11)

**Comment by lsdsjy** [comment]
Thanks!
prettier-plugin-stylus@0.1.0
